enum {
	BLANK_CHAR = 0,

	PLAYER,
	WUMPUS_AWAKEN,
	WUMPUS_SLEEPING1,
	WUMPUS_SLEEPING2,
	ARROW,

	TOP_BORDER__LEFT,
	TOP_BORDER__RIGHT,
	BOTTOM_BORDER__LEFT,
	BOTTOM_BORDER__RIGHT,
	LEFT_BORDER__BOTTOM,
	LEFT_BORDER__TOP,
	RIGHT_BORDER__BOTTOM,
	RIGHT_BORDER__TOP,

	CORNER_BOTTOM_LEFT,
	CORNER_BOTTOM_RIGHT,
	CORNER_TOP_LEFT,
	CORNER_TOP_RIGHT,

	OPEN_FLOOR,
	HIDDEN_FLOOR,
};
